title: "Pod 22.PX.X"
email: fellowship@mlh.io
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio website!
baseurl: "tabaaza.github.io" 
url: "tabaaza.github.io" 
twitter_username: mlhacks
github_username:  mlh-fellowship

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg